---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"
  tags:
    - canary
    - canary_preflight

- name: Assert required config values are set
  assert:
    that: canary_config_addr != 0
    msg: "canary_config_addr needs to be set"
  tags:
    - canary
    - canary_preflight

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/grafana/loki/releases/latest"
        method: GET
        return_content: True
        status_code: 200
        body_format: json
        validate_certs: False
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5
      tags:
        - canary
        - canary_preflight

    - name: "Set canary version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        canary_version: "{{ _latest_release.json.tag_name[1:] }}"
      tags:
        - canary
        - canary_preflight
  when:
    - canary_version == "latest"

- name: "Get checksum list"
  set_fact:
    __canary_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + canary_version + '/SHA256SUMS', wantlist=True) | list }}"
  run_once: True
  tags:
    - canary
    - canary_preflight

- name: "Get checksum for {{ go_system }} {{ go_arch }} architecture"
  set_fact:
    __canary_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __canary_checksums }}"
  tags:
    - canary
    - canary_preflight
  when:
    - "('canary-' + go_system + '-' + go_arch + '.zip') in item"
